version: '3.5'
services:
  openwrt-overture-build:
    image: "openwrtorg/sdk:x86_64-19.07.7"
    container_name: openwrt-overture-build
    volumes:
     - ./bin:/home/build/openwrt/bin
     - ./key-build:/home/build/openwrt/key-build
     - ./:/home/build/openwrt/package/overture
     - ./build.sh:/home/build/openwrt/build.sh
    command: "./build.sh"