name: overture-openwrt

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc
          

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: aparcar/action-openwrt-sdk@composite
        env:
          ARCH: ${{ matrix.arch }}
      - name: Prepare targets
        id: po2lmo
        run: |
          REP=$(basename "${REPF}")
          mv -vf ../src "package/${REP}"
          test -d "package/${REP}/tools/po2lmo"
      - name: Prebuild po2lmo host tool
        if: success()
        run: |
          REP=$(basename "${REPF}")
          pushd "package/${REP}/tools/po2lmo"
          make && sudo make install
      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/packages/*.ipk
