name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    env:
      PKG: overture
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc
          - aarch64_generic
          

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: cielpy/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: overture
      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/base/*.ipk
